### ISSUE TITLE
Simultaneous calls into actor

### ISSUE THREAD

**Issue by jackbond** [Azure/service-fabric-services-and-actors-dotnet#29] opened 2017-07-10 20:23 UTC
I'm seeing some very strange behavior where it appears an actor is simultaneously handing two different calls. My logging is showing the following...

16:52:34 Call begins on Node 1
16:53:28 Call begins on Node 2
16:53:34 Call ends on Node 2
16:58:01 Call ends on Node 1

The fact that the call on Node 2 begins a minute after the Node 1 seems like perhaps a timeout has occurred? If Service Fabric moves an actor to a different node, what happens to in progress calls? This has got my team really spooked, because we didn't think this was possible. Thanks.

**Comment by VipulM-MSFT** [comment] 2017-07-10 20:28
They may be for different ActorId or different Actor Service instance. In addition to the actor id, in your logging add the service and partitioning information from the ServiceContext (service name, partition id).

**Comment by jackbond** [comment] 2017-07-10 21:20
@VipulM-MSFT They definitely have the same ActorId, it just so happened that I had logged the additional info...

CheckoutActorServiceType [NodeType (General)] [NodeInstanceId (131432575815913307)] [PartitionId (81880f51-5b55-483c-8cbb-c3bc34c1a6f4)])

CheckoutActorServiceType [NodeType (General)] [NodeInstanceId (131432575913914198)] [PartitionId (81880f51-5b55-483c-8cbb-c3bc34c1a6f4)])

We have been beating our brains out trying to figure out how we were ending up with conflicting data, because we were confident that the SF actor framework wouldn't allow this to happen. I'm not 100% sure what you mean by "different Actor Service instance." The code was definitely running on two different nodes (in analytics we see different "cloud_RoleInstance"s). Any clue what might be happening? Thanks.

**Comment by VipulM-MSFT** [comment] 2017-07-10 22:02
What is the version of the framework and can you post information about your service? 

Get-ServiceFabricServiceName <PartitionId> (https://docs.microsoft.com/en-us/powershell/module/servicefabric/get-servicefabricservicename?view=azureservicefabricps)

and then 

Get-ServiceFabricServiceDescription <ServiceName> (https://docs.microsoft.com/en-us/powershell/module/servicefabric/get-servicefabricservicedescription?view=azureservicefabricps)

It is also possible that the failover did happen and your nodes are out of sync with respect to the time.

**Comment by grahamehorner** [comment] 2017-07-10 22:17
@VipulM-MSFT it's interesting you mentioned the time of nodes, is there anything within ServiceFabric that could monitor this with the cluster? I've seen a few VMs have time lag?

**Comment by jackbond** [comment] 2017-07-10 22:26
@VipulM-MSFT Cluster info:

5.6.220.9494
2012-R2-Datacenter
.NET 4.7
All running in Azure (not onsite) so I'd be surprised if there was any sort of time issue.

FabricClientSettings : {
                       ClientFriendlyName                   : PowerShell-44db8291-c2b9-4741-aff4-e24b18e8a06f
                       PartitionLocationCacheLimit          : 100000
                       PartitionLocationCacheBucketCount    : 1024
                       ServiceChangePollInterval            : 00:02:00
                       ConnectionInitializationTimeout      : 00:00:02
                       KeepAliveInterval                    : 00:00:20
                       ConnectionIdleTimeout                : 00:00:00
                       HealthOperationTimeout               : 00:02:00
                       HealthReportSendInterval             : 00:00:00
                       HealthReportRetrySendInterval        : 00:00:30
                       NotificationGatewayConnectionTimeout : 00:00:30
                       NotificationCacheUpdateTimeout       : 00:00:30
                       AuthTokenBufferSize                  : 4096
                       }
GatewayInformation   : {
                       NodeAddress                          : 10.0.0.8:19000
                       NodeId                               : e98cfec6cf20c9ae955acb368cc5b74f
                       NodeInstanceId                       : 131432578244664359
                       NodeName                             : _General_4
                       }


ServiceKind                  : Stateful
PartitionScheme              : UniformInt64Range
PlacementConstraints         : None
PlacementPolicies            : {}
LoadMetrics                  : {}
IsDefaultMoveCostSpecified   : True
DefaultMoveCost              : Zero
CorrelatedServices           : {}
PartitionLowKey              : -9223372036854775808
PartitionHighKey             : 9223372036854775807
PartitionCount               : 50
HasPersistedState            : False
TargetReplicaSetSize         : 3
MinReplicaSetSize            : 3
ReplicaRestartWaitDuration   : 00:30:00
QuorumLossWaitDuration       : 37201.09:59:01
StandByReplicaKeepDuration   : 7.00:00:00
Kind                         : Stateful
ServiceTypeName              : CheckoutActorServiceType
ApplicationName              : fabric:/ServiceFabric.Deploy.Checkout
ServiceName                  : fabric:/ServiceFabric.Deploy.Checkout/CheckoutActorService
PartitionSchemeDescription   : System.Fabric.Description.UniformInt64RangePartitionSchemeDescription
InitializationData           : {}
Metrics                      : {}
Correlations                 : {}
ServiceDnsName               : 
ServicePackageActivationMode : SharedProcess

**Comment by VipulM-MSFT** [comment] 2017-07-10 22:40
@grahamehorner - no there isn't any specific tool. We do work fine with clock skews as long as the clocks do not drift at a different rate. @xunlu can you provide more details.

@jackbond - the service seems fine. Other than the possibility of the node clock skews, it is possible that the failover happened and your thread is still running. The runtime does not wait to drain the call, it will not allow state changes as we take away the partition RW status so the state management calls will fail, but the thread may continue. @harahma - can we create an issue to allow for an option to drain the pending actor calls before allowing the change role to continue?

**Comment by VipulM-MSFT** [comment] 2017-07-10 22:41
@jackbond if you have the traces from the cluster and the time range we can verify the theory, feel free to sync up on private message with @harahma  and send him the cluster information.

**Comment by jackbond** [comment] 2017-07-11 14:30
@VipulM-MSFT "can we create an issue to allow for an option to drain the pending actor calls before allowing the change role to continue"

Definitely. I have to admit, I'm a bit stunned this isn't the default. I realize this would complicate moving an actor, but with the current behavior, it appears you need to do a lot of defensive coding. Alternatively, would it be possible to trigger an exception within the actor to stop it from processing, which bubbles up to the caller? Also, can you confirm that we'd see the same type of behavior when a reliable service is moved? Thanks.

**Comment by VipulM-MSFT** [comment] 2017-07-11 16:23
The reliable services sends a cancellation token on RunAsync and so does the ActorService. We wait for RunAsync to complete. However if you have things in-flight in the reliable services and complete RunAsync, the state machines will move on. However the in-flight operations cannot modify the state in both reliable services and actor service.

Waiting for the active operations can have potential in terms of the availability of the service. The new operations will have to wait until the existing ones drain, new primary is elected and the existing operations retry. It is also possible that if the communication stack is closed, reply cannot be sent even for the existing in-flight operations requiring the clients to retry them anyway. With that, coordinated close on the default stack is possible at the expense of potentially impacting the availability.

**Comment by jackbond** [comment] 2017-07-11 16:28
@VipulM-MSFT I'm putting in a support request right now. Just to clarify, can you confirm that the current behavior is NOT to drain pending actor calls, that those calls will continue running, and that the calls will be retried on the new primary?

**Comment by VipulM-MSFT** [comment] 2017-07-11 16:33
@jackbond - yes. Yes do open the support request to verify that that's what happened in your behavior. We will open an issue for the feature request.

**Comment by amanbha** [comment] 2017-11-22 18:54
Closing this issue as this is not a bug and is expected in distributed computing, feel free to reopen this one or create a new issue if you need further help on this.

**Closed by amanbha** 2017-11-22 18:54 UTC
